version: '3'
services:
  gitea:
    image: gitea.cn/gitea/gitea:1.21.2
    container_name: ${CONTAINER_NAME}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=${PANEL_DB_HOST}:3306
      - GITEA__database__NAME=${PANEL_DB_NAME}
      - GITEA__database__USER=${PANEL_DB_USER}
      - GITEA__database__PASSWD=${PANEL_DB_USER_PASSWORD}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
      - "${PANEL_APP_PORT_SSH}:22"
    labels:
      createdBy: "Apps"

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: default-runner
    environment:
      - GITEA_RUNNER_NAME=default-runner
      - GITEA_INSTANCE_URL=https://${GITEA_DOMAIN}/
      - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN}
      - GITEA_RUNNER_JOB_CONTAINER_NETWORK=${CONTAINER_NETWORK}
      # add.1 容器内指定配置文件路径
      - CONFIG_FILE=/config.yaml
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./default-runner/config.yaml:/config.yaml
      - ./default-runner/data:/data
      - ./default-runner/cache:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true